config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :profile, only: [:edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy

  validates_presence_of :user_id, :post_id, :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :friend_of_poster?, only: :create
  before_action :owner_of_comment?, only: :destroy

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      redirect_to posts_path, notice: "Commented!"
    else
      redirect_to posts_path, alert: "Error commenting"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    flash[:notice] = "Comment deleted."
    redirect_to posts_path
  end

  private

    def comment_params
      params.require(:comment).permit(:post_id, :content)
    end

    def owner_of_comment?
      comment = current_user.comments.find_by(id: params[:id], post_id: params[:post_id])
      redirect_to posts_path if comment.nil?
    end

    def friend_of_poster?
      post = Post.find_by(id: params[:comment][:post_id])
      post_creator = User.find_by(id: post.user_id) if post
      friendships = FriendRequest.where(user_id: post_creator.id).where(friend_id: current_user.id).where(accepted: true) + FriendRequest.where(user_id: current_user.id).where(friend_id: post_creator.id).where(accepted: true) if post_creator
      not_friends = friendships.empty? if post_creator
      current_user_is_poster = current_user.id == post_creator.id if post_creator
      redirect_to posts_path if not_friends && !(current_user_is_poster)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="comment-container">
	<p class="comment-gravatar"><%= gravatar_for(comment.user, size:30) %></p>
	<div class="name-and-comment">
		<p><%= link_to comment.user.full_name, user_path(comment.user) %></p>
		<p><%= comment.content %></p>
	</div><br>
  <div class="likes-and-time">
		<p><% if current_user.has_liked_this?(comment) %>
		     <%= link_to "Unlike", comment_like_path(post, id: current_user.id), method: :delete %>
		   <% else %>
		     <%= link_to "Like", comment_likes_path(comment), method: :post %>
		   <% end %>
		   <span> &#183; <%= pluralize(comment.likes.size, 'like') %></span></p>
		<p> &#183; Commented <%= time_ago_in_words(comment.created_at) %> ago.</p>
	</div>
  <% if comment.user.id == current_user.id %>
    <p>&nbsp;<%= link_to "Delete", comment_path(id: comment.id), method: :delete %></p>
  <% end %>
</li>