config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :profile, only: [:edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :friend_requests
  has_many :received_friend_requests, class_name: "FriendRequest", foreign_key: "friend_id", dependent: :destroy

  has_many :added_friends, -> { where(friend_requests: {accepted: true}) }, through: :friend_requests, source: :friend
  has_many :received_friends, -> { where(friend_requests: {accepted: true}) }, through: :received_friend_requests, source: :user

  has_many :pending_added_friends,   -> { where(friend_requests: { accepted: false }) },
           through: :friend_requests, source: :friend
  has_many :pending_friend_requesters, -> { where(friend_requests: { accepted: false }) },
           through: :received_friend_requests, source: :user

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one :profile, dependent: :destroy

  after_create :build_empty_profile
  after_create :send_welcome_email

  def timeline
    Post.where("user_id IN (?) OR user_id = ?", added_friend_ids, id) | Post.where("user_id IN (?) OR user_id = ?", received_friend_ids, id)
  end

  def full_name
    unless profile.first_name.blank? || profile.last_name.blank?
      return "#{profile.first_name} #{profile.last_name}"
    end
    email
  end

  def friends_with?(different_user)
    (added_friends + received_friends).include?(different_user)
  end

  def pending_friends?(different_user)
    (pending_added_friends + pending_friend_requesters).include?(different_user)
  end

  def has_liked_this?(likeable)
    likeable.likes.where(user_id: id).blank? ? false : true
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  private

    def build_empty_profile
      Profile.create!(user: self)
    end

    def send_welcome_email
      UserMailer.welcome_email(self).deliver
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="users-index">
	<h1>Users</h1>

	<table>
		<% @users.each do |user| %>
		  <tr class="users-table-row">
		    <td><%= gravatar_for(user, size: 75) %></td>
		    <td id="user-name"><%= link_to user.full_name, user_path(user) %></td>
		    <td id="friend-status">
	    		<% if current_user.friends_with?(user) %>
	          <p class="btn-primary">Friends</p>
	        <% elsif current_user.pending_friends?(user) %>
	          <p class="btn-primary">Pending</p>
	        <% elsif current_user.id == user.id %>
	        <% else %>
	         	<p class="btn-primary"><%= link_to "Add friend", friend_requests_path(friend_id: user.id), method: :post %></p>
	        <% end %>
		    </td>
		  </tr>
		<% end %>
	</table>
</div>

app/views/users/show.html.erb
<div class="user-show">
	<h1><%= @user.full_name %></h1>
	<%= gravatar_for(@user, size: 250) %><br>
	<% if @user.id == current_user.id %>
		<%= link_to "Edit Account", edit_user_registration_path %>
		<%= link_to "Edit Profile", edit_profile_path %>
	<% end %>
	<h3>Recent posts</h3>
</div>
<%= render @user.posts %>