config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :profile, only: [:edit, :update]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates_presence_of :user_id, :content
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user?, only: :destroy

  def index
    @posts = current_user.timeline
    @post = current_user.posts.build
    @comment = current_user.comments.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to posts_path
    else
      flash[:alert] = "Error posting"
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "Post deleted."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def correct_user?
    post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post-container">
  <p class="post-gravatar"><%= gravatar_for(post.user, size:30) %></p>
	<div class="name-and-comment">
  	<p><%= link_to post.user.full_name, user_path(post.user) %></p>
	  <p><%= post.content %></p>
  </div><br>
  <div class="likes-and-time">
		<p><% if current_user.has_liked_this?(post) %>
		     <%= link_to "Unlike", post_like_path(post, id: current_user.id), method: :delete %>
		   <% else %>
		     <%= link_to "Like", post_likes_path(post), method: :post %>
		   <% end %>
		   <span> &#183; <%= pluralize(post.likes.size, 'like') %></span></p>
  	<p> &#183; Posted <%= time_ago_in_words(post.created_at) %> ago.</p>
  </div>
  <% if post.user.id == current_user.id %>
    <p>&nbsp;<%= link_to "Delete", post_path(id: post.id), method: :delete %></p>
  <% end %>
  <%= render post.comments %>
  <p><%= render 'shared/comment_form', post: post %></p>
</div>

app/views/posts/index.html.erb
<%= render 'shared/post_form' %>
<% if @posts.any? %>
  <%= render @posts %>
<% end %>